"""add event_id

Revision ID: 5325e962d747
Revises: b265af05ec4b
Create Date: 2025-12-22 17:19:10.454165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5325e962d747"
down_revision: Union[str, Sequence[str], None] = "b265af05ec4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tickets', sa.Column('event_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'tickets', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###

    with op.batch_alter_table("tickets") as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_tickets_event_id_events", "events", ["event_id"], ["id"]
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'tickets', type_='foreignkey')
    # op.drop_column('tickets', 'event_id')
    # ### end Alembic commands ###

    with op.batch_alter_table("tickets") as batch_op:
        batch_op.drop_constraint("fk_tickets_event_id_events", type_="foreignkey")
        batch_op.drop_column("event_id")
